/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int BEGIN = 8;
  /** RegularExpression Id. */
  int END = 9;
  /** RegularExpression Id. */
  int DO = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int THEN = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int SEMI = 14;
  /** RegularExpression Id. */
  int ASSIGN = 15;
  /** RegularExpression Id. */
  int CLASS = 16;
  /** RegularExpression Id. */
  int PUBLIC = 17;
  /** RegularExpression Id. */
  int STATIC = 18;
  /** RegularExpression Id. */
  int VOID = 19;
  /** RegularExpression Id. */
  int MAIN = 20;
  /** RegularExpression Id. */
  int NEW = 21;
  /** RegularExpression Id. */
  int EXTENDS = 22;
  /** RegularExpression Id. */
  int RETURN = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int INT = 25;
  /** RegularExpression Id. */
  int BOOLEAN = 26;
  /** RegularExpression Id. */
  int PRINT = 27;
  /** RegularExpression Id. */
  int LENGTH = 28;
  /** RegularExpression Id. */
  int TRUE = 29;
  /** RegularExpression Id. */
  int FALSE = 30;
  /** RegularExpression Id. */
  int THIS = 31;
  /** RegularExpression Id. */
  int OP_AND = 32;
  /** RegularExpression Id. */
  int OP_LESS = 33;
  /** RegularExpression Id. */
  int OP_ADD = 34;
  /** RegularExpression Id. */
  int OP_SUB = 35;
  /** RegularExpression Id. */
  int OP_MULT = 36;
  /** RegularExpression Id. */
  int LETTER = 37;
  /** RegularExpression Id. */
  int ID = 38;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"while\"",
    "\"begin\"",
    "\"end\"",
    "\"do\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\";\"",
    "\"=\"",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"new\"",
    "\"extends\"",
    "\"return\"",
    "\"String\"",
    "\"int\"",
    "\"boolean\"",
    "\"System.out.println\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<LETTER>",
    "<ID>",
    "<INTEGER_LITERAL>",
    "\"{\"",
    "\"(\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\"}\"",
    "\",\"",
    "\"/[\"",
    "\"!\"",
    "\".\"",
  };

}
